sudo: required

language: go

os:
    - linux

go:
    - 1.6.x
    - 1.7.x
    - 1.8rc1

services:
    - postgresql

env:
   - PREST_PG_USER=postgres PREST_PG_DATABASE=prest PREST_PG_PORT=5432 PREST_CONF=../../testdata/prest.toml

before_install:
   - go get -u github.com/kardianos/govendor
   - govendor sync

before_script:
    - sh testdata/schema.sh

script:
    - sh test.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
